project:
  type: website
  output-dir: docs
  
website:
  title: "Time series model"
  navbar:
    left:
      - href: index.qmd
      - href: Forecasting.qmd
      - href: SARIMA.qmd
    tools:
      - icon: github
        text: Github
        href: https://github.com/Loccx78vn/Forecasting_time_series
      - icon: twitter
        text: Another projects
        href: https://rpubs.com/loccx
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Loc cao"

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    toc: true

editor: source

