project:
  type: website
  output-dir: docs
  
website:
  title: "MY WEB SITE"
  navbar:
    left:
      - href: Forecasting.qmd
        text: ARIMA model
      - href: EnsembleML.qmd
        text: Ensemble Machine Learning
    tools:
      - icon: github
        text: Github
        href: https://github.com/Loccx78vn/Quarto
      - icon: twitter
        text: Another projects
        href: https://rpubs.com/loccx
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Loc cao"

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    toc: true

editor: source

