project:
  type: website
  output-dir: docs
  
website:
  title: "Cao Xuân Lộc"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: timeseries.qmd
        text: Time series
      - href: Forecasting.qmd
      - href: SARIMA.qmd
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Loc cao"

format:
  html:
    theme: Flatly
    toc: true

editor: source

